// <auto-generated />
using Hotel.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel.models.Login", b =>
                {
                    b.Property<int>("Id");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Hotel.models.Pather", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("DateBorn");

                    b.Property<int>("IdHigh");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Sex");

                    b.HasKey("Id");

                    b.ToTable("Pather");
                });

            modelBuilder.Entity("Hotel.models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("DateIn");

                    b.Property<string>("Dateout");

                    b.Property<int>("Document");

                    b.Property<string>("Lastname");

                    b.Property<string>("Name");

                    b.Property<string>("Sex");

                    b.Property<string>("TypeRoom");

                    b.HasKey("Id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Hotel.models.Room", b =>
                {
                    b.Property<int>("Id");

                    b.Property<bool>("Avidable");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Hotel.models.Roomreser", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("IdRoom");

                    b.HasKey("Id");

                    b.ToTable("Roomreser");
                });

            modelBuilder.Entity("Hotel.models.Users", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
